/**:
  ros__parameters:
    mass: 35.5
    model: swift
    inertial:
      ixx: 0.8061
      iyy: 1.1413
      izz: 1.5599
      ixy: -0.0059
      ixz: 0.0005
      iyz: -0.0113
    cog: [0, 0, 0.0]
    cob: [0.0, 0.0, 0.02489]
    volume: 0.0364
    length: 0.74
    height: 0.425
    width: 0.64
    base_link: base_link
    Ma:
      [13, 0, 0, 0, 0, 0,
      0, 30, 0, 0, 0, 0,
      0, 0, 45, 0, 0, 0,
      0, 0, 0, 10.2, 0, 0,
      0, 0, 0, 0, 10.37, 0,
      0, 0, 0, 0, 0, 7.35]
    linear_damping: [-22.8, -30.95, -50.26, -95.05, -98.0, -11.13]
    quad_damping: [ -28.43, -55.98, -137.5, -0.0, -0.0, -0.00]
    density: 1028.0
