# This file does not need to follow the ROS 2 yaml syntax as it
# is not parsed by the ROS 2 API
inertial_frame_id: world
waypoints:
  -
    point: [2.5, 0.0, -2.0]
    max_forward_speed: 0.6
    heading: 0
    use_fixed_heading: False
  -
    point: [12.5, 3.0, -4.0]
    max_forward_speed: 0.7
    heading: 0
    use_fixed_heading: False

  -
    point: [17.5, 7.0, -8.0]
    max_forward_speed: 0.7
    heading: 0
    use_fixed_heading: False
  -
    point: [20.0, 10.0, -14.0]
    max_forward_speed: 0.7
    heading: 0
    use_fixed_heading: False
